# Fix colors
# set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
# For right looking Nvim colorscheme
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g update-environment "VIRTUAL_ENV"


# set -g prefix C-a

# change index
set -g base-index 1             # start indexing windows at 1 instead of 0
setw -g pane-base-index 1
set -g escape-time 0            # zero-out escape time delay
set -g mouse on                 # enable mouse support
set -g set-clipboard on         # use system clipboard

# ----
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5


bind -n C-h previous-window
bind -n C-l next-window


bind -r m resize-pane -Z


bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane


# Install Tmux Plugin Mangaer
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
# set -g @plugin 'dracula/tmux'


# Configuration status line
#
# Общий цвет статус-бара (фон и текст)
# Light grey: #B3B1ADBF // 75% alpha

set -g @black "#0a0e14"
set -g @grey "#b3b1ad"
set -g @yellow "#e6b450"
set -g @orange "#ffb454"
set -g @red "#ff8f40"
set -g @blue "#59c2ff"

# 2. Основной стиль статус-бара
set -g status-style "bg=#{@black},fg=#{@grey}"

# 3. Цвет АКТИВНОГО окна (Исправлено обращение к переменной)
# set-window-option -g window-status-current-style "bg=#0a0e14,fg=#ffb454,bold"


# Цвет неактивных окон
# set-window-option -g window-status-style "bg=#{@black},fg=#{@grey}"

# Активное окно: оранжевый текст, без звездочки
set-window-option -g window-status-current-format "#[fg=#{@orange},bg=#{@black},bold] #I:#W "

# Неактивное окно: серый текст
set-window-option -g window-status-format "#[fg=#{@grey},bg=#{@black}] #I:#W "

# Левая часть
set -g status-left-length 20
set -g status-left "#[fg=#{@yellow},bg=#{@black}]  #S "

# Правая часть
set -g status-right-length 100
# Исправлено: везде добавлена @ перед именами переменных внутри #{}
set -g status-right "#[fg=#{@grey},bg=#{@black}] 󰋊 #(df -h ~ | awk '{print $4}') "
set -ag status-right "#[fg=#{@grey}]  #(free -h | awk '/^Mem:/ {print $4}') "
# set -ag status-right "#[fg=#{@orange}]#( [ -n '$VIRTUAL_ENV' ] && echo \"  $(basename '$VIRTUAL_ENV') \" )"
# set -ag status-right "#[fg=#{@yellow}]  #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '') "

# set -g status-right "#[fg=#B3B1AD,bg=#0a0e14] %Y-%m-%d │ #[fg=#e6b450]%H:%M "
# set -ag status-right "#[fg=magenta]  Py: #(basename \"$VIRTUAL_ENV\" || echo 'none') "

# Интервал обновления (в секундах)
#  󰋊 disk, ram 󰍛  python  


# Start plagin manager
run '~/.tmux/plugins/tpm/tpm'
